const EXTENSION_LANGUAGE: Record<string, string> = {
  ts: "TypeScript",
  tsx: "TypeScript (React)",
  mts: "TypeScript",
  cts: "TypeScript",
  js: "JavaScript",
  jsx: "JavaScript (React)",
  mjs: "JavaScript",
  cjs: "JavaScript",
  py: "Python",
  rb: "Ruby",
  go: "Go",
  rs: "Rust",
  java: "Java",
  kt: "Kotlin",
  swift: "Swift",
  c: "C",
  h: "C header",
  cc: "C++",
  cpp: "C++",
  hpp: "C++ header",
  cs: "C#",
  php: "PHP",
  scala: "Scala",
  sh: "Shell",
  bash: "Shell",
  ps1: "PowerShell",
  sql: "SQL",
  html: "HTML",
  css: "CSS",
  scss: "SCSS",
  less: "Less",
  json: "JSON",
  jsonc: "JSON",
  yaml: "YAML",
  yml: "YAML",
  toml: "TOML",
  xml: "XML",
  md: "Markdown",
  mdx: "MDX",
  graphql: "GraphQL",
  proto: "Protocol Buffers",
  tf: "Terraform",
  dockerfile: "Dockerfile",
  vue: "Vue",
  svelte: "Svelte",
  dart: "Dart",
  ex: "Elixir",
  exs: "Elixir",
  erl: "Erlang",
  hs: "Haskell",
  lua: "Lua",
  r: "R",
  zig: "Zig",
};

export function detectLanguage(path: string): string | null {
  const fileName = path.split("/").pop() ?? path;
  if (/^dockerfile$/i.test(fileName)) return "Dockerfile";
  if (/^makefile$/i.test(fileName)) return "Makefile";
  const extension = fileName.includes(".") ? fileName.split(".").pop()!.toLowerCase() : "";
  return EXTENSION_LANGUAGE[extension] ?? null;
}
