// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  projectId: __t.string().primaryKey().name("project_id"),
  snapshotId: __t.string().name("snapshot_id"),
  runId: __t.string().name("run_id"),
  generatedAt: __t.string().name("generated_at"),
  payloadJson: __t.string().name("payload_json"),
});
