// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const CodebaseArchitecture = __t.object("CodebaseArchitecture", {
  projectId: __t.string(),
  snapshotId: __t.string(),
  runId: __t.string(),
  generatedAt: __t.string(),
  payloadJson: __t.string(),
});
export type CodebaseArchitecture = __Infer<typeof CodebaseArchitecture>;

export const ConceptKnowledge = __t.object("ConceptKnowledge", {
  id: __t.string(),
  userId: __t.string(),
  conceptKey: __t.string(),
  familiarity: __t.string(),
  updatedAt: __t.string(),
});
export type ConceptKnowledge = __Infer<typeof ConceptKnowledge>;

export const ExplanationPreference = __t.object("ExplanationPreference", {
  id: __t.string(),
  userId: __t.string(),
  preferenceKey: __t.string(),
  value: __t.string(),
  updatedAt: __t.string(),
});
export type ExplanationPreference = __Infer<typeof ExplanationPreference>;

export const FeedbackEvent = __t.object("FeedbackEvent", {
  id: __t.string(),
  userId: __t.string(),
  projectId: __t.string(),
  conceptKey: __t.string(),
  componentPath: __t.string(),
  action: __t.string(),
  createdAt: __t.string(),
});
export type FeedbackEvent = __Infer<typeof FeedbackEvent>;

export const ProjectIdentity = __t.object("ProjectIdentity", {
  id: __t.string(),
  userId: __t.string(),
  projectId: __t.string(),
  cwd: __t.string(),
  createdAt: __t.string(),
  updatedAt: __t.string(),
});
export type ProjectIdentity = __Infer<typeof ProjectIdentity>;

export const ProjectKnowledge = __t.object("ProjectKnowledge", {
  id: __t.string(),
  userId: __t.string(),
  projectId: __t.string(),
  componentPath: __t.string(),
  familiarity: __t.string(),
  updatedAt: __t.string(),
});
export type ProjectKnowledge = __Infer<typeof ProjectKnowledge>;

export const UserProfile = __t.object("UserProfile", {
  userId: __t.string(),
  createdAt: __t.string(),
  updatedAt: __t.string(),
});
export type UserProfile = __Infer<typeof UserProfile>;

