// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CacheCodebaseArchitectureReducer from "../cache_codebase_architecture_reducer";
import EnsureUserProfileReducer from "../ensure_user_profile_reducer";
import MapProjectIdentityReducer from "../map_project_identity_reducer";
import RecordFeedbackEventReducer from "../record_feedback_event_reducer";
import SetConceptKnowledgeReducer from "../set_concept_knowledge_reducer";
import SetExplanationPreferenceReducer from "../set_explanation_preference_reducer";
import SetProjectKnowledgeReducer from "../set_project_knowledge_reducer";

export type CacheCodebaseArchitectureParams = __Infer<typeof CacheCodebaseArchitectureReducer>;
export type EnsureUserProfileParams = __Infer<typeof EnsureUserProfileReducer>;
export type MapProjectIdentityParams = __Infer<typeof MapProjectIdentityReducer>;
export type RecordFeedbackEventParams = __Infer<typeof RecordFeedbackEventReducer>;
export type SetConceptKnowledgeParams = __Infer<typeof SetConceptKnowledgeReducer>;
export type SetExplanationPreferenceParams = __Infer<typeof SetExplanationPreferenceReducer>;
export type SetProjectKnowledgeParams = __Infer<typeof SetProjectKnowledgeReducer>;

